/**
 * Database Package - Public API
 *
 * Exports Prisma client and types
 */

export { Prisma, PrismaClient } from '@prisma/client';
export type {
  // Enums
  UserRole,
  PropertyType,
  VehicleType,
  VisitorStatus,
  WalletStatus,
  TransactionType,
  TransactionStatus,
  SlipSize,
  SlipStatus,
  BoatStatus,
  MarinaReservationStatus,
  FacilityType,
  FacilityStatus,
  ReservationStatus,
  RestaurantStatus,
  OrderStatus,
  OrderType,
  CheckInVisibility,
  BadgeRarity,
  BadgeRequirement,
  ChallengeType,
  LeaderboardPeriod,
  MembershipTier,
  BillingCycle,
  MembershipStatus,
  AdType,
  AdStatus,
  // Models
  User,
  Property,
  Vehicle,
  Visitor,
  Wallet,
  Transaction,
  Slip,
  Boat,
  MarinaReservation,
  Facility,
  Reservation,
  Restaurant,
  Order,
  Place,
  PlaceCategory,
  Review,
  CheckIn,
  UserGamification,
  Badge,
  UserBadge,
  Challenge,
  PlaceChallenge,
  CompletedChallenge,
  Leaderboard,
  BusinessMembership,
  PlaceAd,
} from '@prisma/client';
